import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored third-party code — not ours, not lintable. Both are served as static
    // assets rather than bundled (see the README in each directory), so nothing here
    // ever reaches the app's own type or lint boundary.
    "public/draco/**",
    "public/tarteaucitron/**",
    // A git worktree parked here is a second checkout of this same repo. Linting it
    // grades another branch's tree, and its own copy of the vendored Draco decoder is
    // not covered by the ignore above — which is enough to fail `pnpm lint` outright.
    ".claude/**",
    // Generated by `pnpm prismic:codegen` from the models — never hand-edited.
    "prismicio-types.d.ts",
  ]),
]);

export default eslintConfig;
