// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

type ArticleDocumentDataBodySlice = ArticleSectionSlice

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
	/**
	 * Titre field in *Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Titre de l'article
	 * - **API ID Path**: article.title
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Extrait (liste + meta description) field in *Article*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Resume court affiche sur la liste et utilise comme meta description
	 * - **API ID Path**: article.excerpt
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	excerpt: prismic.RichTextField;
	
	/**
	 * Date de publication field in *Article*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.publish_date
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	publish_date: prismic.DateField;
	
	/**
	 * Visuel de couverture field in *Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.cover
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover: prismic.ImageField<never>;
	
	/**
	 * Auteur (optionnel) field in *Article*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.author
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	author: prismic.ContentRelationshipField<"author">;
	
	/**
	 * Corps de l'article field in *Article*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article.body[]
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<ArticleDocumentDataBodySlice>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ArticleDocumentData>, "article", Lang>;

/**
 * Content for Auteur documents
 */
interface AuthorDocumentData {
	/**
	 * Nom field in *Auteur*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Jean-Noe Kollo
	 * - **API ID Path**: author.name
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Role field in *Auteur*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Geek & philosophe
	 * - **API ID Path**: author.role
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;
	
	/**
	 * Avatar field in *Auteur*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: author.avatar
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	avatar: prismic.ImageField<never>;
}

/**
 * Auteur document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Item in *Étude de cas → Tags*
 */
export interface CaseStudyDocumentDataTagsItem {
	/**
	 * Tag field in *Étude de cas → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: SEO
	 * - **API ID Path**: case_study.tags[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

type CaseStudyDocumentDataBodySlice = CaseChapterSlice

/**
 * Content for Étude de cas documents
 */
interface CaseStudyDocumentData {
	/**
	 * Titre field in *Étude de cas*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Industrie & B2B
	 * - **API ID Path**: case_study.title
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Ordre d'affichage (croissant) sur la page Cases field in *Étude de cas*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 10
	 * - **API ID Path**: case_study.display_order
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	display_order: prismic.NumberField;
	
	/**
	 * Nature de la mission field in *Étude de cas*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Plateformes de marque
	 * - **API ID Path**: case_study.kind
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	kind: prismic.KeyTextField;
	
	/**
	 * Client (optionnel — laisser vide si l'engagement est sous NDA) field in *Étude de cas*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Nom du client
	 * - **API ID Path**: case_study.client
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	client: prismic.KeyTextField;
	
	/**
	 * Résumé field in *Étude de cas*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Ce qu'on a fait et ce que ça a changé
	 * - **API ID Path**: case_study.summary
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	summary: prismic.RichTextField;
	
	/**
	 * Tags field in *Étude de cas*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.tags[]
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<CaseStudyDocumentDataTagsItem>>;
	
	/**
	 * Visuel de couverture field in *Étude de cas*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.cover
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover: prismic.ImageField<never>;
	
	/**
	 * Corps de l'étude de cas field in *Étude de cas*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.body[]
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<CaseStudyDocumentDataBodySlice>;
}

/**
 * Étude de cas document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CaseStudyDocumentData>, "case_study", Lang>;

type PageDocumentDataSlicesSlice = HomeSceneSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Titre SEO (optionnel) field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: BIG EMOTION — L'agence B!G qui fait dire wow.
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta description (optionnel) field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: On ne fait pas des sites web. On cree de l'impact.
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * Corps de la page field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = ArticleDocument | AuthorDocument | CaseStudyDocument | PageDocument;

/**
 * Primary content in *ArticleSection → Par défaut → Primary*
 */
export interface ArticleSectionSliceDefaultPrimary {
	/**
	 * Titre de la section field in *ArticleSection → Par défaut → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Un sous-titre
	 * - **API ID Path**: article_section.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Texte field in *ArticleSection → Par défaut → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Le contenu de la section
	 * - **API ID Path**: article_section.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Visuel (optionnel) field in *ArticleSection → Par défaut → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: article_section.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Par défaut variation for ArticleSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Titre, texte riche, visuel optionnel.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleSectionSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ArticleSectionSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ArticleSection*
 */
type ArticleSectionSliceVariation = ArticleSectionSliceDefault

/**
 * ArticleSection Shared Slice
 *
 * - **API ID**: `article_section`
 * - **Description**: Une section du corps d'un article : titre, texte riche et visuel optionnel.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ArticleSectionSlice = prismic.SharedSlice<"article_section", ArticleSectionSliceVariation>;

/**
 * Primary content in *CaseChapter → Par défaut → Primary*
 */
export interface CaseChapterSliceDefaultPrimary {
	/**
	 * Titre du chapitre field in *CaseChapter → Par défaut → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Le probleme
	 * - **API ID Path**: case_chapter.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Texte field in *CaseChapter → Par défaut → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Le contenu du chapitre
	 * - **API ID Path**: case_chapter.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Visuel (optionnel) field in *CaseChapter → Par défaut → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_chapter.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Par défaut variation for CaseChapter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Titre, texte riche, visuel optionnel.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseChapterSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CaseChapterSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CaseChapter*
 */
type CaseChapterSliceVariation = CaseChapterSliceDefault

/**
 * CaseChapter Shared Slice
 *
 * - **API ID**: `case_chapter`
 * - **Description**: Un chapitre d'étude de cas : titre, texte riche et visuel optionnel. Seule slice du corps d'une étude de cas.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseChapterSlice = prismic.SharedSlice<"case_chapter", CaseChapterSliceVariation>;

/**
 * Item in *HomeScene → Par defaut → Primary → Lignes du titre*
 */
export interface HomeSceneSliceDefaultPrimaryHeadingItem {
	/**
	 * Ligne field in *HomeScene → Par defaut → Primary → Lignes du titre*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: L'agence
	 * - **API ID Path**: home_scene.default.primary.heading[].line
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	line: prismic.KeyTextField;
}

/**
 * Primary content in *HomeScene → Par defaut → Primary*
 */
export interface HomeSceneSliceDefaultPrimary {
	/**
	 * Identifiant de la scene (choregraphie 3D) field in *HomeScene → Par defaut → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: approach
	 * - **API ID Path**: home_scene.default.primary.scene_id
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	scene_id: prismic.SelectField<"intro" | "approach" | "cases" | "culture" | "louder" | "final", "filled">;
	
	/**
	 * Lignes du titre field in *HomeScene → Par defaut → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_scene.default.primary.heading[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	heading: prismic.GroupField<Simplify<HomeSceneSliceDefaultPrimaryHeadingItem>>;
	
	/**
	 * Texte (optionnel) field in *HomeScene → Par defaut → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: On part de la reaction, puis on remonte tout le fil pour l'obtenir.
	 * - **API ID Path**: home_scene.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	body: prismic.KeyTextField;
	
	/**
	 * Afficher la poignee sociale field in *HomeScene → Par defaut → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: home_scene.default.primary.social_handle
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	social_handle: prismic.BooleanField;
}

/**
 * Par defaut variation for HomeScene Slice
 *
 * - **API ID**: `default`
 * - **Description**: Titre empile visible, texte optionnel, poignee sociale optionnelle.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomeSceneSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HomeSceneSliceDefaultPrimary>, never>;

/**
 * Primary content in *HomeScene → Introduction (wordmark 3D) → Primary*
 */
export interface HomeSceneSliceIntroHeroPrimary {
	/**
	 * Identifiant de la scene (choregraphie 3D) field in *HomeScene → Introduction (wordmark 3D) → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: intro
	 * - **API ID Path**: home_scene.introHero.primary.scene_id
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	scene_id: prismic.SelectField<"intro" | "approach" | "cases" | "culture" | "louder" | "final", "filled">;
	
	/**
	 * Signature (nom accessible du h1) field in *HomeScene → Introduction (wordmark 3D) → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: L'agence B!G qui fait dire wow.
	 * - **API ID Path**: home_scene.introHero.primary.tagline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tagline: prismic.KeyTextField;
	
	/**
	 * Texte (optionnel) field in *HomeScene → Introduction (wordmark 3D) → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Big Emotion est un studio creatif digital first...
	 * - **API ID Path**: home_scene.introHero.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	body: prismic.KeyTextField;
}

/**
 * Introduction (wordmark 3D) variation for HomeScene Slice
 *
 * - **API ID**: `introHero`
 * - **Description**: Scene d'ouverture : le titre visible est le wordmark 3D, cette variante ne rend qu'un h1 accessible.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomeSceneSliceIntroHero = prismic.SharedSliceVariation<"introHero", Simplify<HomeSceneSliceIntroHeroPrimary>, never>;

/**
 * Slice variation for *HomeScene*
 */
type HomeSceneSliceVariation = HomeSceneSliceDefault | HomeSceneSliceIntroHero

/**
 * HomeScene Shared Slice
 *
 * - **API ID**: `home_scene`
 * - **Description**: Un temps fort du scroll spine de la Home : titre empile, texte optionnel, poignee sociale optionnelle.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HomeSceneSlice = prismic.SharedSlice<"home_scene", HomeSceneSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			ArticleDocument,
			ArticleDocumentData,
			ArticleDocumentDataBodySlice,
			AuthorDocument,
			AuthorDocumentData,
			CaseStudyDocument,
			CaseStudyDocumentData,
			CaseStudyDocumentDataTagsItem,
			CaseStudyDocumentDataBodySlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			ArticleSectionSlice,
			ArticleSectionSliceDefaultPrimary,
			ArticleSectionSliceVariation,
			ArticleSectionSliceDefault,
			CaseChapterSlice,
			CaseChapterSliceDefaultPrimary,
			CaseChapterSliceVariation,
			CaseChapterSliceDefault,
			HomeSceneSlice,
			HomeSceneSliceDefaultPrimaryHeadingItem,
			HomeSceneSliceDefaultPrimary,
			HomeSceneSliceIntroHeroPrimary,
			HomeSceneSliceVariation,
			HomeSceneSliceDefault,
			HomeSceneSliceIntroHero
		}
	}
}