// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Étude de cas → Tags*
 */
export interface CaseStudyDocumentDataTagsItem {
	/**
	 * Tag field in *Étude de cas → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: SEO
	 * - **API ID Path**: case_study.tags[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
}

type CaseStudyDocumentDataBodySlice = CaseChapterSlice

/**
 * Content for Étude de cas documents
 */
interface CaseStudyDocumentData {
	/**
	 * Titre field in *Étude de cas*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Industrie & B2B
	 * - **API ID Path**: case_study.title
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Nature de la mission field in *Étude de cas*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Plateformes de marque
	 * - **API ID Path**: case_study.kind
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	kind: prismic.KeyTextField;
	
	/**
	 * Client (optionnel — laisser vide si l'engagement est sous NDA) field in *Étude de cas*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Nom du client
	 * - **API ID Path**: case_study.client
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	client: prismic.KeyTextField;
	
	/**
	 * Résumé field in *Étude de cas*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Ce qu'on a fait et ce que ça a changé
	 * - **API ID Path**: case_study.summary
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	summary: prismic.RichTextField;
	
	/**
	 * Tags field in *Étude de cas*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.tags[]
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<CaseStudyDocumentDataTagsItem>>;
	
	/**
	 * Visuel de couverture field in *Étude de cas*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.cover
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	cover: prismic.ImageField<never>;
	
	/**
	 * Corps de l'étude de cas field in *Étude de cas*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_study.body[]
	 * - **Tab**: Principal
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	body: prismic.SliceZone<CaseStudyDocumentDataBodySlice>;
}

/**
 * Étude de cas document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<CaseStudyDocumentData>, "case_study", Lang>;

export type AllDocumentTypes = CaseStudyDocument;

/**
 * Primary content in *CaseChapter → Par défaut → Primary*
 */
export interface CaseChapterSliceDefaultPrimary {
	/**
	 * Titre du chapitre field in *CaseChapter → Par défaut → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Le probleme
	 * - **API ID Path**: case_chapter.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;
	
	/**
	 * Texte field in *CaseChapter → Par défaut → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Le contenu du chapitre
	 * - **API ID Path**: case_chapter.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;
	
	/**
	 * Visuel (optionnel) field in *CaseChapter → Par défaut → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: case_chapter.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Par défaut variation for CaseChapter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Titre, texte riche, visuel optionnel.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseChapterSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CaseChapterSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CaseChapter*
 */
type CaseChapterSliceVariation = CaseChapterSliceDefault

/**
 * CaseChapter Shared Slice
 *
 * - **API ID**: `case_chapter`
 * - **Description**: Un chapitre d'étude de cas : titre, texte riche et visuel optionnel. Seule slice du corps d'une étude de cas.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseChapterSlice = prismic.SharedSlice<"case_chapter", CaseChapterSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			CaseStudyDocument,
			CaseStudyDocumentData,
			CaseStudyDocumentDataTagsItem,
			CaseStudyDocumentDataBodySlice,
			AllDocumentTypes,
			CaseChapterSlice,
			CaseChapterSliceDefaultPrimary,
			CaseChapterSliceVariation,
			CaseChapterSliceDefault
		}
	}
}